import { writable } from 'svelte/store'

export const currentLang = writable<'tr' | 'en'>('tr')

export const translations = {
  tr: {
    appName: 'Soylu IPTV',
    appSubtitle: "Türkiye'nin En İyi IPTV Platformu",
    search: 'Ara',
    searchPlaceholder: 'Kanal ara...',
    channels: 'Kanallar',
    categories: 'Kategoriler',
    countries: 'Ülkeler',
    m3u: 'M3U Dosyası',
    xtream: 'Xtream Kodu',
    download: 'İndir',
    copy: 'Kopyala',
    copied: 'Kopyalandı!',
    username: 'Kullanıcı Adı',
    password: 'Şifre',
    generatePlaylist: 'Oynatma Listesi Oluştur',
    apiEndpoint: 'API Endpoint',
    selectCountry: 'Ülke Seçin',
    selectCategory: 'Kategori Seçin',
    noChannels: 'Kanal bulunamadı',
    totalChannels: 'Toplam Kanal',
    language: 'Dil',
    about: 'Hakkında',
    help: 'Yardım',
    contact: 'İletişim',
    usageInstructions: 'Kullanım Talimatları',
    m3uInstructions: 'M3U oynatıcınızda kullanmak için:',
    xtreamInstructions: 'Xtream Codes desteği olan oynatıcılarda kullanın:',
    tvPlayer: 'TV Oynatıcısında Kullan',
    documentation: 'Dokümantasyon',
  },
  en: {
    appName: 'Soylu IPTV',
    appSubtitle: 'The Best IPTV Platform',
    search: 'Search',
    searchPlaceholder: 'Search channels...',
    channels: 'Channels',
    categories: 'Categories',
    countries: 'Countries',
    m3u: 'M3U File',
    xtream: 'Xtream Code',
    download: 'Download',
    copy: 'Copy',
    copied: 'Copied!',
    username: 'Username',
    password: 'Password',
    generatePlaylist: 'Generate Playlist',
    apiEndpoint: 'API Endpoint',
    selectCountry: 'Select Country',
    selectCategory: 'Select Category',
    noChannels: 'No channels found',
    totalChannels: 'Total Channels',
    language: 'Language',
    about: 'About',
    help: 'Help',
    contact: 'Contact',
    usageInstructions: 'Usage Instructions',
    m3uInstructions: 'To use on your M3U player:',
    xtreamInstructions: 'Use on Xtream Codes compatible players:',
    tvPlayer: 'Use in TV Player',
    documentation: 'Documentation',
  },
}

export function t(lang: 'tr' | 'en', key: keyof typeof translations.tr): string {
  return translations[lang][key] || key
}
