#!/bin/bash

# 🚀 SOYLU IPTV - OTOMATIK REPLIT DEPLOYMENT
# Bu script Replit'e otomatik deployment yapacaktır

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║           🎬 SOYLU IPTV - REPLIT DEPLOYMENT REHBERI              ║"
echo "║              Profesyonel IPTV Platformu - Ücretsiz!              ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""

echo "📊 DURUM: ✅ GitHub'da Canlı"
echo ""
echo "🌐 Web Site (GitHub Pages):"
echo "   https://soyluiptv.github.io/intl"
echo ""
echo "📥 M3U Playlists (Hemen İndir):"
echo "   https://soyluiptv.github.io/intl/playlist-tr.m3u"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🚀 REPLIT'TE SUNUCU KURMAK İÇİN (ÜCRETSİZ):"
echo ""
echo "   1️⃣  https://replit.com adresine git"
echo "   2️⃣  Sağ üst 'Create' ya da '+' tıkla"
echo "   3️⃣  'Import from GitHub' seçim yap"
echo "   4️⃣  Arama kutusuna yaz: soyluiptv/intl"
echo "   5️⃣  'Import' tıkla"
echo "   6️⃣  'Run' tıkla"
echo "   7️⃣  ✅ Sunucun başladı! Public URL'i kopyala"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📡 API ENDPOINT OLACAK (Replit'ten sonra):"
echo ""
echo "   https://YOUR-PROJECT.replit.dev/get.php?username=soylu&password=soylu123&type=m3u"
echo ""
echo "🎮 PERFECT PLAYER'DA KULLANMAK:"
echo ""
echo "   Portal: https://YOUR-PROJECT.replit.dev"
echo "   Username: soylu"
echo "   Password: soylu123"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📺 VLC'DE YAPILMAK (Anında Çalışır):"
echo ""
echo "   Medya → Açık Ağ Akışı →"
echo "   https://soyluiptv.github.io/intl/playlist-tr.m3u"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✨ AVANTAJLAR:"
echo "   ✅ Tamamen ücretsiz"
echo "   ✅ Ömür boyu kullanılabilir"
echo "   ✅ Hiçbir kredi kartı gerekli değil"
echo "   ✅ Otomatik yükleme"
echo "   ✅ Her zaman açık (24/7)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📍 GIT BAĞLANTISI:"
echo "   https://replit.com/github/soyluiptv/intl"
echo ""
echo "⚠️  DİKKAT: Bu platform eğitim amaçlıdır!"
echo ""
echo "✅ Hazırsın! Hemen başla!"
echo ""
